// src/app/(authenticated)/driver/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { DataTable } from "primereact/datatable";
import { Column } from "primereact/column";
import { Button } from "primereact/button";
import { InputText } from "primereact/inputtext";
import { Tag } from "primereact/tag";
import { Menu } from "primereact/menu";
import { Toast } from "primereact/toast";
import { ConfirmDialog, confirmDialog } from "primereact/confirmdialog";
import { FilterMatchMode } from "primereact/api";
import { Avatar } from "primereact/avatar";
import DriverService from "@/services/DriverService";

interface Driver {
  id: number;
  first_name: string;
  last_name: string;
  name: string;
  email: string;
  birth_date: string;
  dateBirth: string;
  verified: boolean;
  otp_verified: boolean;
  status: string;
  picture?: string;
  public_id?: string;
  verificationProgress?: string;
  verificationStatus?: string;
  imageLoaded: boolean;
}

export default function DriverListPage() {
  const router = useRouter();
  const toast = useRef<Toast>(null);
  const menu = useRef<Menu>(null);
  const driverService = new DriverService();

  const [drivers, setDrivers] = useState<Driver[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedDriver, setSelectedDriver] = useState<Driver | null>(null);
  const [globalFilterValue, setGlobalFilterValue] = useState("");
  const [filters, setFilters] = useState({
    global: { value: null, matchMode: FilterMatchMode.CONTAINS },
    name: { value: null, matchMode: FilterMatchMode.STARTS_WITH },
    email: { value: null, matchMode: FilterMatchMode.CONTAINS },
    status: { value: null, matchMode: FilterMatchMode.EQUALS },
  });

  const menuItems = [
    {
      label: "Verify",
      icon: "pi pi-check",
      command: () => {
        if (selectedDriver) {
          router.push(`/driver/${selectedDriver.id}`);
        }
      },
    },
    {
      label: "Delete",
      icon: "pi pi-trash",
      command: () => {
        if (selectedDriver) {
          confirmDelete(selectedDriver);
        }
      },
    },
  ];

  useEffect(() => {
    loadDrivers();
  }, []);

  const loadDrivers = async () => {
    try {
      setLoading(true);
      const data = await driverService.getAllDrivers();
      const formattedDrivers = data.map((driver: any) => ({
        ...driver,
        name: `${driver.first_name} ${driver.last_name}`,
        dateBirth: driver.birth_date || new Date().toISOString().split("T")[0],
        email: driver.email,
        verified: driver.otp_verified,
        status: driver.status?.toLowerCase(),
        picture: driver.picture,
        public_id: driver.public_id,
        verificationProgress: driver.verificationProgress,
        verificationStatus: driver.verificationStatus,
        imageLoaded: !!driver.picture,
      }));
      setDrivers(formattedDrivers);
    } catch (error) {
      console.error("Failed to load drivers:", error);
      toast.current?.show({
        severity: "error",
        summary: "Error",
        detail: "Failed to load drivers",
        life: 3000,
      });
    } finally {
      setLoading(false);
    }
  };

  const confirmDelete = (driver: Driver) => {
    confirmDialog({
      message: `Are you sure you want to delete ${driver.name}?`,
      header: "Confirm Deletion",
      icon: "pi pi-exclamation-triangle",
      acceptClassName: "p-button-danger",
      accept: () => handleDelete(driver),
    });
  };

  const handleDelete = async (driver: Driver) => {
    try {
      await driverService.deleteDriver(driver.id);
      toast.current?.show({
        severity: "success",
        summary: "Success",
        detail: `Driver ${driver.name} deleted successfully`,
        life: 3000,
      });
      loadDrivers();
    } catch (error: any) {
      toast.current?.show({
        severity: "error",
        summary: "Delete Failed",
        detail: error.message || "Failed to delete driver",
        life: 3000,
      });
    }
  };

  const onGlobalFilterChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    const _filters: any = { ...filters };
    _filters.global.value = value;
    setFilters(_filters);
    setGlobalFilterValue(value);
  };

  const clearFilter = () => {
    setGlobalFilterValue("");
    setFilters({
      global: { value: null, matchMode: FilterMatchMode.CONTAINS },
      name: { value: null, matchMode: FilterMatchMode.STARTS_WITH },
      email: { value: null, matchMode: FilterMatchMode.CONTAINS },
      status: { value: null, matchMode: FilterMatchMode.EQUALS },
    });
  };

  const toggleMenu = (event: React.MouseEvent, driver: Driver) => {
    setSelectedDriver(driver);
    menu.current?.toggle(event);
  };

  const formatDate = (value: string) => {
    if (!value) return "N/A";
    return new Date(value).toLocaleDateString("en-US", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
    });
  };

  const getInitials = (first: string, last: string) => {
    return ((first?.charAt(0) || "") + (last?.charAt(0) || "")).toUpperCase();
  };

  const nameBodyTemplate = (rowData: Driver) => {
    return (
      <div className="flex align-items-center gap-2">
        {rowData.imageLoaded && rowData.picture ? (
          <Avatar
            image={rowData.picture}
            size="normal"
            shape="circle"
            onError={() => {
              const updatedDrivers = drivers.map((d) =>
                d.id === rowData.id ? { ...d, imageLoaded: false } : d
              );
              setDrivers(updatedDrivers);
            }}
          />
        ) : (
          <Avatar
            label={getInitials(rowData.first_name, rowData.last_name)}
            size="normal"
            shape="circle"
            style={{ backgroundColor: "#9c27b0", color: "#ffffff" }}
          />
        )}
        <span>{rowData.name}</span>
      </div>
    );
  };

  const verifiedBodyTemplate = (rowData: Driver) => {
    return (
      <Tag
        value={rowData.verified ? "Verified" : "Not Verified"}
        severity={rowData.verified ? "success" : "warning"}
      />
    );
  };

  const actionBodyTemplate = (rowData: Driver) => {
    return (
      <Button
        icon="pi pi-ellipsis-v"
        rounded
        text
        onClick={(e) => toggleMenu(e, rowData)}
      />
    );
  };

  const header = (
    <div className="flex justify-content-between flex-column sm:flex-row">
      <Button
        type="button"
        icon="pi pi-filter-slash"
        label="Clear"
        outlined
        onClick={clearFilter}
        className="mb-2"
      />
      <span className="p-input-icon-left mb-2">
        <i className="pi pi-search" />
        <InputText
          value={globalFilterValue}
          onChange={onGlobalFilterChange}
          placeholder="Search drivers..."
          style={{ width: "100%" }}
        />
      </span>
    </div>
  );

  return (
    <div className="grid">
      <Toast ref={toast} />
      <ConfirmDialog />

      <div className="col-12">
        <div className="card">
          <h5>Driver Management</h5>
          <DataTable
            value={drivers}
            paginator
            rows={10}
            dataKey="id"
            filters={filters}
            filterDisplay="menu"
            loading={loading}
            responsiveLayout="scroll"
            globalFilterFields={["name", "email", "status"]}
            header={header}
            emptyMessage="No drivers found."
            rowHover
          >
            <Column
              field="name"
              header="Name"
              body={nameBodyTemplate}
              sortable
              filter
              filterPlaceholder="Search by name"
              style={{ minWidth: "14rem" }}
            />
            <Column
              field="dateBirth"
              header="Date of Birth"
              body={(rowData) => formatDate(rowData.dateBirth)}
              sortable
              style={{ minWidth: "12rem" }}
            />
            <Column
              field="email"
              header="Email"
              sortable
              filter
              filterPlaceholder="Search by email"
              style={{ minWidth: "12rem" }}
            />
            <Column
              field="verificationProgress"
              header="Verification Progress"
              sortable
              style={{ minWidth: "10rem" }}
            />
            <Column
              field="verified"
              header="Verified"
              body={verifiedBodyTemplate}
              sortable
              style={{ minWidth: "10rem" }}
            />
            <Column
              body={actionBodyTemplate}
              exportable={false}
              style={{ minWidth: "8rem" }}
              header="Action"
            />
          </DataTable>

          <Menu model={menuItems} popup ref={menu} />
        </div>
      </div>
    </div>
  );
}

// src/pages/driver/index.vue
<script lang="ts">
import { FilterMatchMode, FilterOperator } from 'primevue/api';
import DriverService from '~~/services/DriverService';

export default {
  data() {
    return {
      drivers: null,
      filters: null,
      loading: true,
      selectedDriver: null,
      deleteDialogVisible: false,
      driverToDelete: null,
      overlayMenuItems: [
        {
          label: 'Verify',
          icon: 'pi pi-check',
          command: () => {
            this.verifyDriver(this.selectedDriver);
          }
        },
        {
          label: 'Delete',
          icon: 'pi pi-trash',
          command: () => {
            this.confirmDelete(this.selectedDriver);
          }
        }
      ]
    };
  },
  driverService: null,
  created() {
    this.driverService = new DriverService();
    this.initFilters(); // Initialize filters when component is created
  },
  mounted() {
    this.loadDrivers();
  },
  methods: {
    loadDrivers() {
      this.loading = true;
      this.driverService.getAllDrivers().then(data => {
        this.drivers = data.map(driver => ({
          ...driver,
          name: `${driver.first_name} ${driver.last_name}`,
          dateBirth: driver.birth_date || new Date().toISOString().split('T')[0],
          email: driver.email,
          verified: driver.otp_verified,
          status: driver.status?.toLowerCase(),
          picture: driver.picture,
          public_id: driver.public_id,
          verificationProgress: driver.verificationProgress,
          verificationStatus: driver.verificationStatus,
          imageLoaded: !!driver.picture,
          deleting: false
        }));
        this.loading = false;
      }).catch(error => {
        console.error('Failed to load drivers:', error);
        this.loading = false;
      });
    },

    initFilters() {
      this.filters = {
        'global': { value: null, matchMode: FilterMatchMode.CONTAINS },
        'name': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }] },
        'email': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.CONTAINS }] },
        'dateBirth': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.DATE_IS }] },
        'verified': { value: null, matchMode: FilterMatchMode.EQUALS },
        'status': { operator: FilterOperator.OR, constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }] }
      };
    },

    clearFilter() {
      this.initFilters();
    },

    formatDate(value) {
      if (!value) return 'N/A';
      return new Date(value).toLocaleDateString('en-US', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric'
      });
    },

    toggleMenu(event, selectedDriver) {
      this.selectedDriver = selectedDriver;
      this.$refs.menu.toggle(event);
    },

    getInitials(first: string, last: string) {
      return ((first?.charAt(0) || '') + (last?.charAt(0) || '')).toUpperCase();
    },

    confirmDelete(driver: any) {
      this.driverToDelete = driver;
      this.deleteDialogVisible = true;
    },

    onImageError(event: Event, data: any) {
      data.imageLoaded = false;
      event.target.style.display = 'none';
    },

    async deleteDriver() {
      if (!this.driverToDelete) {
        this.$toast.add({
          severity: 'warn',
          summary: 'Warning',
          detail: 'No driver selected for deletion',
          life: 3000
        });
        return;
      }

      this.driverToDelete.deleting = true;

      try {
        await this.driverService.deleteDriver(this.driverToDelete.id);

        this.drivers = this.drivers.filter(d => d.id !== this.driverToDelete.id);

        this.$toast.add({
          severity: 'success',
          summary: 'Success',
          detail: `Driver ${this.driverToDelete.name} deleted successfully`,
          life: 3000
        });

        console.log('Driver deleted successfully:', this.driverToDelete.name);
      } catch (error) {
        console.error('Failed to delete driver:', error);

        this.$toast.add({
          severity: 'error',
          summary: 'Delete Failed',
          detail: error.response?.data?.message || error.message || 'Failed to delete driver. Please try again.',
          life: 5000
        });
      } finally {
        this.driverToDelete.deleting = false;
        this.deleteDialogVisible = false;
        this.driverToDelete = null;
      }
    },

    confirmDelete(driver) {
      this.$confirm.require({
        message: `Are you sure you want to delete ${driver.name}?`,
        header: 'Confirm Deletion',
        icon: 'pi pi-exclamation-triangle',
        acceptLabel: 'Yes',
        rejectLabel: 'No',
        accept: async () => {
          this.driverToDelete = driver;
          await this.deleteDriver();
        }
      });
    },

    verifyDriver(driver) {
      if (driver && driver.id) {
        navigateTo(`/driver/${driver.id}`);
      } else {
        console.error('Driver or driver ID not found');
      }
    }
  }
};
</script>

<template>
  <div class="grid">
    <Toast />
    <div class="col-12">
      <div class="card">
        <h5>Driver Management</h5>
        <DataTable
          v-model:filters="filters"
          :value="drivers"
          :paginator="true"
          class="p-datatable-gridlines"
          :rows="10"
          data-key="id"
          :row-hover="true"
          filter-display="menu"
          :loading="loading"
          responsive-layout="scroll"
          :global-filter-fields="['name', 'email', 'status']"
        >
          <template #header>
            <div class="flex justify-content-between flex-column sm:flex-row">
              <Button
                type="button"
                icon="pi pi-filter-slash"
                label="Clear"
                class="p-button-outlined mb-2"
                @click="clearFilter()"
              />
              <span class="p-input-icon-left mb-2">
                <i class="pi pi-search" />
                <InputText
                  v-model="filters['global'].value"
                  placeholder="Search drivers..."
                  style="width: 100%"
                />
              </span>
            </div>
          </template>

          <template #empty>
            No drivers found.
          </template>

          <!-- <template #loading>
            Loading drivers data. Please wait.
          </template> -->

          <Column
            header="Name"
            field="name"
            :show-filter-match-modes="false"
            :filter-menu-style="{ width: '14rem' }"
            sortable
            style="min-width:14rem"
          >
            <template #body="{ data }">
              <div style="display: flex; align-items: center;">
                <div class="avatar-wrapper">
                  <img
                    v-if="data.imageLoaded && data.picture"
                    :src="data.picture"
                    width="32"
                    height="32"
                    style="vertical-align: middle; border-radius: 50%; object-fit: cover;"
                    :alt="data.first_name"
                    @error="onImageError($event, data)"
                  >
                  <span
                    v-if="!data.imageLoaded || !data.picture"
                    class="fallback-avatar"
                  >
                    {{ getInitials(data.first_name, data.last_name) }}
                  </span>
                </div>
                <span style="margin-left: .5em; vertical-align: middle" class="image-text">
                  {{ data.name }}
                </span>
              </div>
            </template>
          </Column>

          <Column
            field="dateBirth"
            sortable
            header="Date of Birth"
            style="min-width:12rem"
          >
            <template #body="{ data }">
              {{ formatDate(data.dateBirth) }}
            </template>
          </Column>

          <Column
            header="Email"
            filter-field="email"
            field="email"
            sortable
            style="min-width:12rem"
          >
            <template #body="{ data }">
              {{ data.email }}
            </template>
          </Column>

          <Column
            field="verificationProgress"
            header="Verification Progress"
            data-type="text"
            sortable
            body-class="text-center"
            style="min-width:10rem"
          >
            <template #body="{ data }">
              {{ data.verificationProgress || 'Not Started' }}
            </template>
          </Column>

          <Column body-class="text-center">
            <template #header>
              <span class="text-center w-full">
                Action
              </span>
            </template>
            <template #body="{ data }">
              <Menu ref="menu" :model="overlayMenuItems" :popup="true" class="w-fit px-2" />
              <Button
                :icon="data.deleting ? 'pi pi-spin pi-spinner' : 'pi pi-ellipsis-v'"
                class="p-button-rounded p-button-text p-2"
                @click="toggleMenu($event, data)"
              />
            </template>
          </Column>
        </DataTable>
      </div>
    </div>

    <Dialog
      v-model:visible="deleteDialogVisible"
      :style="{ width: '450px' }"
      header="Confirm Delete"
      :modal="true"
      class="p-fluid"
    >
      <div class="flex align-items-center justify-content-center my-3">
        <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem; color: var(--orange-500)"/>
        <span v-if="driverToDelete">
          Are you sure you want to delete <b>{{ driverToDelete.name }}</b>?
        </span>
      </div>

      <template #footer>
        <Button
          label="No"
          icon="pi pi-times"
          class="p-button-text"
          @click="cancelDelete"
        />
        <Button
          label="Yes"
          icon="pi pi-check"
          class="p-button-danger"
          @click="deleteDriver"
        />
      </template>
    </Dialog>
    <ConfirmDialog />
  </div>
</template>

<style scoped lang="scss">
.avatar-wrapper {
  position: relative;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.fallback-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background-color: #ccc;
  color: #fff;
  font-weight: bold;
  font-size: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
