// src/app/(authenticated)/order/[id]/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import { Card } from "primereact/card";
import { Button } from "primereact/button";
import { Toast } from "primereact/toast";
import { Tag } from "primereact/tag";
import { Divider } from "primereact/divider";
import { Timeline } from "primereact/timeline";
import OrderService from "@/services/OrderService";

export default function OrderDetailPage() {
  const params = useParams();
  const router = useRouter();
  const toast = useRef<Toast>(null);
  const orderService = new OrderService();

  const [order, setOrder] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [generatingCode, setGeneratingCode] = useState(false);

  useEffect(() => {
    if (params.id) {
      loadOrder();
    }
  }, [params.id]);

  const loadOrder = async () => {
    try {
      setLoading(true);
      const data = await orderService.getOrderDetails(Number(params.id));
      setOrder(data);
    } catch (error) {
      console.error("Failed to load order:", error);
      toast.current?.show({
        severity: "error",
        summary: "Error",
        detail: "Failed to load order details",
        life: 3000,
      });
    } finally {
      setLoading(false);
    }
  };

  const generateOrderCode = async () => {
    try {
      setGeneratingCode(true);
      await orderService.generateOrderCode(Number(params.id));
      toast.current?.show({
        severity: "success",
        summary: "Success",
        detail: "Order verification code generated successfully",
        life: 3000,
      });
      // Reload order to get updated data
      loadOrder();
    } catch (error: any) {
      toast.current?.show({
        severity: "error",
        summary: "Error",
        detail: error.message || "Failed to generate order code",
        life: 3000,
      });
    } finally {
      setGeneratingCode(false);
    }
  };

  const formatCurrency = (value: number) => {
    if (typeof value !== "number") return "";
    const price = value
      .toLocaleString("en-NG", { style: "currency", currency: "NGN" })
      .split("");
    price.splice(1, 0, " ");
    return price.join("");
  };

  const getSeverity = (status: string): "success" | "info" | "warning" | "danger" | undefined => {
    switch (status) {
      case "PENDING":
        return "warning";
      case "CONFIRMED":
        return "info";
      case "IN_TRANSIT":
        return "info";
      case "DELIVERED":
        return "success";
      case "CANCELLED":
        return "danger";
      case "IN_PAYMENT":
        return "info";
      case "PICKUP":
        return "warning";
      default:
        return undefined;
    }
  };

  if (loading) {
    return (
      <div className="flex justify-content-center align-items-center" style={{ minHeight: "400px" }}>
        <i className="pi pi-spin pi-spinner" style={{ fontSize: "3rem" }} />
      </div>
    );
  }

  if (!order) {
    return (
      <div className="card">
        <h5>Order not found</h5>
        <Button label="Back to List" icon="pi pi-arrow-left" onClick={() => router.push("/order")} />
      </div>
    );
  }

  const timelineEvents = [
    { status: "Order Placed", date: order.created_at, icon: "pi pi-shopping-cart" },
    { status: "Confirmed", date: order.confirmed_at, icon: "pi pi-check" },
    { status: "In Transit", date: order.in_transit_at, icon: "pi pi-truck" },
    { status: "Delivered", date: order.delivered_at, icon: "pi pi-check-circle" },
  ].filter((event) => event.date);

  return (
    <div className="grid">
      <Toast ref={toast} />

      <div className="col-12">
        <Card>
          <div className="flex justify-content-between align-items-center mb-4">
            <div className="flex align-items-center gap-3">
              <Button
                icon="pi pi-arrow-left"
                rounded
                text
                onClick={() => router.push("/order")}
              />
              <div>
                <h5 className="m-0">Order #{order.order_id}</h5>
                <Tag
                  value={order.order_status}
                  severity={getSeverity(order.order_status)}
                  className="mt-2"
                />
              </div>
            </div>
            <div className="flex gap-2">
              <Button
                label="Generate Code"
                icon="pi pi-qrcode"
                onClick={generateOrderCode}
                loading={generatingCode}
                disabled={order.order_status === "DELIVERED" || order.order_status === "CANCELLED"}
              />
            </div>
          </div>

          <Divider />

          <div className="grid">
            <div className="col-12 md:col-6">
              <Card title="Customer Information" className="h-full">
                <div className="field">
                  <label className="font-semibold">Name</label>
                  <p>
                    {order.user?.first_name} {order.user?.last_name}
                  </p>
                </div>
                <div className="field">
                  <label className="font-semibold">Email</label>
                  <p>{order.user?.email || "N/A"}</p>
                </div>
                <div className="field">
                  <label className="font-semibold">Phone</label>
                  <p>{order.user?.phone_number || "N/A"}</p>
                </div>
              </Card>
            </div>

            <div className="col-12 md:col-6">
              <Card title="Driver Information" className="h-full">
                <div className="field">
                  <label className="font-semibold">Name</label>
                  <p>
                    {order.driver?.first_name} {order.driver?.last_name}
                  </p>
                </div>
                <div className="field">
                  <label className="font-semibold">Email</label>
                  <p>{order.driver?.email || "N/A"}</p>
                </div>
                <div className="field">
                  <label className="font-semibold">Phone</label>
                  <p>{order.driver?.phone_number || "N/A"}</p>
                </div>
              </Card>
            </div>

            <div className="col-12">
              <Card title="Package Details">
                <div className="grid">
                  <div className="col-12 md:col-4">
                    <label className="font-semibold">Delivery Type</label>
                    <p>{order.package?.delivery_type || "N/A"}</p>
                  </div>
                  <div className="col-12 md:col-4">
                    <label className="font-semibold">Weight</label>
                    <p>{order.package?.weight || "N/A"}</p>
                  </div>
                  <div className="col-12 md:col-4">
                    <label className="font-semibold">Dimensions</label>
                    <p>{order.package?.dimensions || "N/A"}</p>
                  </div>
                  <div className="col-12">
                    <label className="font-semibold">Description</label>
                    <p>{order.package?.description || "N/A"}</p>
                  </div>
                </div>
              </Card>
            </div>

            <div className="col-12 md:col-6">
              <Card title="Pickup Location">
                <p>{order.pickup_address || "N/A"}</p>
              </Card>
            </div>

            <div className="col-12 md:col-6">
              <Card title="Delivery Location">
                <p>{order.delivery_address || "N/A"}</p>
              </Card>
            </div>

            <div className="col-12 md:col-6">
              <Card title="Payment Information">
                <div className="field">
                  <label className="font-semibold">Total Amount</label>
                  <p className="text-2xl font-bold text-primary">
                    {formatCurrency(order.price_fees)}
                  </p>
                </div>
                <div className="field">
                  <label className="font-semibold">Payment Method</label>
                  <p>{order.payment_method || "N/A"}</p>
                </div>
                <div className="field">
                  <label className="font-semibold">Payment Status</label>
                  <Tag
                    value={order.payment_status || "Pending"}
                    severity={order.payment_status === "PAID" ? "success" : "warning"}
                  />
                </div>
              </Card>
            </div>

            <div className="col-12 md:col-6">
              <Card title="Order Timeline">
                {timelineEvents.length > 0 ? (
                  <Timeline
                    value={timelineEvents}
                    content={(item) => (
                      <div>
                        <p className="font-semibold">{item.status}</p>
                        <p className="text-sm text-500">
                          {new Date(item.date).toLocaleString()}
                        </p>
                      </div>
                    )}
                    marker={(item) => (
                      <span
                        className="flex w-2rem h-2rem align-items-center justify-content-center text-white border-circle z-1 shadow-1"
                        style={{ backgroundColor: "var(--primary-color)" }}
                      >
                        <i className={item.icon} />
                      </span>
                    )}
                  />
                ) : (
                  <p>No timeline data available</p>
                )}
              </Card>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}

// src/pages/order/[id].vue
<script lang="ts">
import { FilterMatchMode, FilterOperator } from 'primevue/api';
import OrderService from '~~/services/OrderService';

export default {
  data() {
    return {
      order: null,
      filters1: null,
      filters2: {},
      loading1: true,
      loading2: true,
      idFrozen: false,
      products: null,
      expandedRows: [],
      statuses: [
        'unqualified', 'qualified', 'new', 'negotiation', 'renewal', 'proposal'
      ],
      representatives: [
        { name: 'Amy Elsner', image: 'amyelsner.png' },
        { name: 'Anna Fali', image: 'annafali.png' },
        { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
        { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
        { name: 'Elwin Sharvill', image: 'elwinsharvill.png' },
        { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        { name: 'Ivan Magalhaes', image: 'ivanmagalhaes.png' },
        { name: 'Onyama Limba', image: 'onyamalimba.png' },
        { name: 'Stephen Shaw', image: 'stephenshaw.png' },
        { name: 'XuXue Feng', image: 'xuxuefeng.png' }
      ]
    };
  },
  orderService: null,
  created() {
    this.orderService = new OrderService();
  },
  mounted() {
    this.loadOrderDetail();
  },
  methods: {
    loadOrderDetail() {
      this.loading = true;
      this.orderService.getOrderDetails(this.$route.params.id).then(data => {
        console.log(data);
        this.order = {
          orderInfo: {
            customer_name: `${data.user.first_name} ${data.user.last_name}`,
            driver_name: `${data.driver.first_name} ${data.driver.last_name}`,
            total_payment: data?.price_fees,
            status: data.order_status,
            package_category: data.package.delivery_type
          },
          packageInfo: {
            image: data.package.image_url,
            deliveryType: data.package.delivery_type,
            pickupLocation: `${data.sender_address.landmark_address} - ${data.sender_address.pickup_address}`,
            dropoffAddress: `${data.receiver_address.landmark_address} - ${data.receiver_address.dropoff_address}`,
            senderName: data.sender_address.sender_name,
            senderPhone: data.sender_address.sender_phone,
            size: 'Medium',
            description: data.package.description,
            applyInsurance: true
          }
        };
        this.loading = false;
      }).catch(error => {
        console.error('Failed to load drivers:', error);
        this.loading = false;
      });
    },
    formatCurrency(value: number) {
      const price = value.toLocaleString('en-NG', { style: 'currency', currency: 'NGN' }).split('');
      price.splice(1, 0, ' ');
      return price.join('');
    },
    formatDate(value: Date) {
      return value.toLocaleDateString('en-US', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric'
      });
    },
    getSeverity(status: string) {
      switch (status) {
        case 'pending': return 'warning';
        case 'confirmed': return 'info';
        case 'in transit': return 'primary';
        case 'delivered': return 'success';
        case 'cancelled': return 'danger';
        default: return null;
      }
    },
    getIcon(status: string) {
      switch (status) {
        case 'pending': return 'pi pi-exclamation-triangle';
        case 'confirmed': return 'pi pi-info-circle';
        case 'in transit': return 'pi pi-spinner';
        case 'delivered': return 'pi pi-check';
        case 'cancelled': return 'pi pi-times';
        default: return 'pi pi-info-circle';
      }
    }
  }
};
</script>

<template>
  <div class="grid">
    <div v-if="loading" class="loading-overlay">
      <div>
        <i class="pi pi-spin pi-spinner" style="font-size: 4rem" />
      </div>
    </div>
    <div class="col-12">
      <div v-if="order" class="card">
        <div class="flex justify-content-between align-items-center mb-3">
          <h4>Details</h4>
        </div>
        <div class="card mb-4">
          <div class="card-header">
            <h6 class="text-primary mb-3">
              <i class="pi pi-truck mr-2" />
              Order Detail
            </h6>
          </div>
          <div class="border-2 surface-border p-4 border-round">
            <section class="mb-5">
              <div class="grid">
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Customer Name
                  </p>
                  <p class="font-medium">
                    {{ order.orderInfo.customer_name }}
                  </p>
                </div>
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Customer Phone
                  </p>
                  <p class="font-medium">
                    {{ order.packageInfo.senderPhone }}
                  </p>
                </div>
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Driver Name
                  </p>
                  <p class="font-medium">
                    {{ order.orderInfo.driver_name }}
                  </p>
                </div>
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Pickup Location
                  </p>
                  <p class="font-medium">
                    {{ order.packageInfo.pickupLocation }}
                  </p>
                </div>
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Destination
                  </p>
                  <p class="font-medium">
                    {{ order.packageInfo.dropoffAddress }}
                  </p>
                </div>
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Total Payment
                  </p>
                  <p class="font-medium text-green-600">
                    {{ formatCurrency(order.orderInfo.total_payment) }}
                  </p>
                </div>
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Status
                  </p>
                  <Tag
                    :value="order.orderInfo.status"
                    :severity="getSeverity(order.orderInfo.status)"
                    :icon="getIcon(order.orderInfo.status)"
                  />
                </div>
                <div class="col-12 md:col-6 mb-2">
                  <p class="text-sm text-500 mb-1">
                    Package Category
                  </p>
                  <p class="font-medium">
                    {{ order.orderInfo.package_category }}
                  </p>
                </div>
              </div>
            </section>
          </div>
        </div>

        <div class="card mb-4">
          <div class="card-header">
            <h6 class="text-primary mb-3">
              <i class="pi pi-box mr-2" />
              Package Detail
            </h6>
          </div>
          <div class="border-2 surface-border p-4 border-round">
            <section>
              <div class="grid">
                <!-- Gambar kiri -->
                <div class="col-12 md:col-4 flex justify-content-start">
                  <img
                    :src="order.packageInfo.image"
                    alt="Package"
                    class="w-full md:w-10 border-round shadow-2 cursor-pointer"
                    @click="showImage = true"
                  >
                </div>

                <!-- Detail kanan -->
                <div class="col-12 md:col-8 grid">
                  <div class="col-12 md:col-6 mb-2">
                    <p class="text-sm text-500 mb-1">
                      Delivery Type
                    </p>
                    <p class="font-medium">
                      {{ order.packageInfo.deliveryType }}
                    </p>
                  </div>
                  <div class="col-12 md:col-6 mb-2">
                    <p class="text-sm text-500 mb-1">
                      Sender Name
                    </p>
                    <p class="font-medium">
                      {{ order.packageInfo.senderName }}
                    </p>
                  </div>
                  <div class="col-12 md:col-6 mb-2">
                    <p class="text-sm text-500 mb-1">
                      Package Size
                    </p>
                    <p class="font-medium">
                      {{ order.packageInfo.size }}
                    </p>
                  </div>
                  <div class="col-12 mb-2">
                    <p class="text-sm text-500 mb-1">
                      Description
                    </p>
                    <p class="font-medium">
                      {{ order.packageInfo.description }}
                    </p>
                  </div>
                  <div class="col-12 mb-2">
                    <p class="text-sm text-500 mb-1">
                      Apply Insurance
                    </p>
                    <Tag
                      :value="order.packageInfo.applyInsurance ? 'Yes' : 'No'"
                      :severity="order.packageInfo.applyInsurance ? 'success' : 'danger'"
                      :icon="order.packageInfo.applyInsurance ? 'pi pi-check' : 'pi pi-times'"
                    />
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>

        <!-- Modal Gambar -->
        <Dialog v-model:visible="showImage" modal header="Package Image" :style="{ width: '50vw' }">
          <img :src="order.packageInfo.image" alt="Package" class="w-full border-round">
        </Dialog>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.loading-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(255, 255, 255, 0.8);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 9999;
}

.customer-badge {
  border-radius: 2px;
  padding: 0.25em 0.5rem;
  text-transform: uppercase;
  font-weight: 700;
  font-size: 12px;
  letter-spacing: 0.3px;

  &.status-qualified {
    background: #c8e6c9;
    color: #256029;
  }

  &.status-unqualified {
    background: #ffcdd2;
    color: #c63737;
  }

  &.status-negotiation {
    background: #feedaf;
    color: #8a5340;
  }

  &.status-new {
    background: #b3e5fc;
    color: #23547b;
  }

  &.status-renewal {
    background: #eccfff;
    color: #694382;
  }

  &.status-proposal {
    background: #ffd8b2;
    color: #805b36;
  }
}

.product-badge {
  border-radius: 2px;
  padding: 0.25em 0.5rem;
  text-transform: uppercase;
  font-weight: 700;
  font-size: 12px;
  letter-spacing: 0.3px;

  &.status-instock {
    background: #c8e6c9;
    color: #256029;
  }

  &.status-outofstock {
    background: #ffcdd2;
    color: #c63737;
  }

  &.status-lowstock {
    background: #feedaf;
    color: #8a5340;
  }
}

.order-badge {
  border-radius: 2px;
  padding: 0.25em 0.5rem;
  text-transform: uppercase;
  font-weight: 700;
  font-size: 12px;
  letter-spacing: 0.3px;

  &.order-delivered {
    background: #c8e6c9;
    color: #256029;
  }

  &.order-cancelled {
    background: #ffcdd2;
    color: #c63737;
  }

  &.order-pending {
    background: #feedaf;
    color: #8a5340;
  }

  &.order-returned {
    background: #eccfff;
    color: #694382;
  }
}
</style>
