// src/pages/voucher/index.vue
<script lang="ts">
import { FilterMatchMode, FilterOperator } from 'primevue/api';
import VoucherService from '~~/services/VoucherService';

export default {
  data() {
    return {
      vouchers: [],
      filters: null,
      loading: true,
      selectedVoucher: null,
      deleteDialogVisible: false,
      voucherToDelete: null,
      overlayMenuItems: [
        {
          label: 'View',
          icon: 'pi pi-eye',
          command: () => {
            this.goToEditVoucher(this.selectedVoucher);
          }
        },
        {
          label: 'Delete',
          icon: 'pi pi-trash',
          command: () => {
            this.confirmDelete(this.selectedVoucher);
          }
        }
      ]
    };
  },
  voucherService: null,
  created() {
    this.voucherService = new VoucherService();
    this.initFilters();
  },
  mounted() {
    this.loadVouchers();
  },
  methods: {
    loadVouchers() {
      this.loading = true;
      this.voucherService.getAllVouchers().then(data => {
        this.vouchers = data.map(voucher => ({
          ...voucher,
          amount: voucher.amount || 0,
          code: voucher.code || '',
          voucherType: voucher.expiry_type.split(' ')[0],
          expiryDate: voucher.expiry_type.split(' ')[1],
          name: voucher.name || '',
          used: voucher.used || 0,
          deleting: false
        }));
        this.loading = false;
      }).catch(error => {
        console.error('Failed to load voucher:', error);
        this.loading = false;
      });
    },

    initFilters() {
      this.filters = {
        'global': { value: null, matchMode: FilterMatchMode.CONTAINS },
        'name': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }] },
        'voucherType': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }] },
        'expiryDate': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }] },
        'amount': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }] },
        'used': { operator: FilterOperator.AND, constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }] }
      };
    },

    clearFilter() {
      this.initFilters();
    },

    formatDate(value) {
      if (!value) return 'N/A';
      return new Date(value).toLocaleDateString('en-US', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric'
      });
    },

    toggleMenu(event, selectedVoucher) {
      this.selectedVoucher = selectedVoucher;
      this.$refs.menu.toggle(event);
    },

    confirmDelete(voucher: any) {
      this.voucherToDelete = voucher;
      this.deleteDialogVisible = true;
    },

    async deleteVoucher() {
      console.log('deleting voucher:', this.voucherToDelete);
      if (!this.voucherToDelete) {
        this.$toast.add({
          severity: 'warn',
          summary: 'Warning',
          detail: 'No voucher selected for deletion',
          life: 3000
        });
        return;
      }

      this.voucherToDelete.deleting = true;

      try {
        await this.voucherService.deleteVoucher(this.voucherToDelete.id);

        this.vouchers = this.vouchers.filter(d => d.id !== this.voucherToDelete.id);

        this.$toast.add({
          severity: 'success',
          summary: 'Success',
          detail: `Voucher ${this.voucherToDelete.name} deleted successfully`,
          life: 3000
        });

        console.log('voucher deleted successfully:', this.voucherToDelete.name);
      } catch (error) {
        console.error('Failed to delete voucher:', error);

        this.$toast.add({
          severity: 'error',
          summary: 'Delete Failed',
          detail: error.response?.data?.message || error.message || 'Failed to delete voucher. Please try again.',
          life: 5000
        });
      } finally {
        this.voucherToDelete.deleting = false;
        this.deleteDialogVisible = false;
        this.voucherToDelete = null;
      }
    },

    confirmDelete(voucher) {
      console.log('confirmDelete', voucher);
      this.$confirm.require({
        message: `Are you sure you want to delete ${voucher.name}?`,
        header: 'Confirm Deletion',
        icon: 'pi pi-exclamation-triangle',
        acceptLabel: 'Yes',
        rejectLabel: 'No',
        accept: async () => {
          this.voucherToDelete = voucher;
          await this.deleteVoucher();
        }
      });
    },

    goToCreateVoucher() {
      navigateTo('/voucher/create');
    },

    goToEditVoucher(voucher) {
      navigateTo(`/voucher/${voucher.id}`);
    }
  }
};
</script>

<template>
  <div class="grid">
    <Toast />
    <div class="col-12">
      <div class="card">
        <h5>Voucher Management</h5>
        <DataTable
          v-model:filters="filters"
          :value="vouchers"
          :paginator="vouchers.length > 10"
          class="p-datatable-gridlines"
          :rows="10"
          data-key="id"
          :row-hover="true"
          filter-display="menu"
          :loading="loading"
          responsive-layout="scroll"
          :global-filter-fields="['name', 'code', 'voucherType', 'expiryDate', 'amount', 'used']"
        >
          <template #header>
            <div class="flex justify-content-between flex-column sm:flex-row">
              <Button
                type="button" icon="pi pi-plus" label="Add"
                class="p-button mb-2"
                @click="goToCreateVoucher"
              />
              <div class="flex gap-3">
                <Button
                  type="button"
                  icon="pi pi-filter-slash"
                  label="Clear"
                  class="p-button-outlined mb-2"
                  @click="clearFilter()"
                />
                <span class="p-input-icon-left mb-2">
                  <i class="pi pi-search" />
                  <InputText
                    v-model="filters['global'].value"
                    placeholder="Search voucher..."
                    style="width: 100%"
                  />
                </span>
              </div>
            </div>
          </template>

          <template #empty>
            No voucher found.
          </template>

          <Column
            header="Name"
            field="name"
            :show-filter-match-modes="false"
            :filter-menu-style="{ width: '14rem' }"
            sortable
            style="min-width:14rem"
          >
            <template #body="{ data }">
              <div style="display: flex; align-items: center;">
                <span style="margin-left: .5em; vertical-align: middle" class="image-text">
                  {{ data.name }}
                </span>
              </div>
            </template>
          </Column>

          <Column
            field="code"
            sortable
            header="Code"
            style="min-width:12rem"
          >
            <template #body="{ data }">
              {{ data.code || "-" }}
            </template>
          </Column>

          <Column
            field="voucherType"
            sortable
            header="Voucher Type"
            style="min-width:12rem"
          >
            <template #body="{ data }">
              <p class="capitalize">
                {{ data.voucherType }}
              </p>
            </template>
          </Column>

          <Column
            header="Expiry Date"
            filter-field="expiryDate"
            field="expiryDate"
            sortable
            style="min-width:12rem"
          >
            <template #body="{ data }">
              {{ data.expiryDate }}
            </template>
          </Column>

          <Column
            header="Amount"
            filter-field="amount"
            field="amount"
            sortable
            style="min-width:8rem"
          >
            <template #body="{ data }">
              {{ data.amount }}
            </template>
          </Column>

          <Column
            header="Used"
            filter-field="used"
            field="used"
            sortable
            style="min-width:8rem"
          >
            <template #body="{ data }">
              {{ data.used }}
            </template>
          </Column>

          <Column body-class="text-center">
            <template #header>
              <span class="text-center w-full">
                Action
              </span>
            </template>
            <template #body="{ data }">
              <Menu ref="menu" :model="overlayMenuItems" :popup="true" class="w-fit px-2" />
              <Button
                :icon="data.deleting ? 'pi pi-spin pi-spinner' : 'pi pi-ellipsis-v'"
                class="p-button-rounded p-button-text p-2"
                @click="toggleMenu($event, data)"
              />
            </template>
          </Column>
        </DataTable>
      </div>
    </div>

    <Dialog
      v-model:visible="deleteDialogVisible"
      :style="{ width: '450px' }"
      header="Confirm Delete"
      :modal="true"
      class="p-fluid"
    >
      <div class="flex align-items-center justify-content-center my-3">
        <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem; color: var(--orange-500)"/>
        <span v-if="voucherToDelete">
          Are you sure you want to delete <b>{{ voucherToDelete.name }}</b>?
        </span>
      </div>

      <template #footer>
        <Button
          label="No"
          icon="pi pi-times"
          class="p-button-text"
        />
        <Button
          label="Yes"
          icon="pi pi-check"
          class="p-button-danger"
          @click="deleteVoucher"
        />
      </template>
    </Dialog>
    <ConfirmDialog />
  </div>
</template>

<style scoped lang="scss">
.avatar-wrapper {
  position: relative;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.fallback-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background-color: #ccc;
  color: #fff;
  font-weight: bold;
  font-size: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>

// src/app/(authenticated)/voucher/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { DataTable } from "primereact/datatable";
import { Column } from "primereact/column";
import { Button } from "primereact/button";
import { InputText } from "primereact/inputtext";
import { Tag } from "primereact/tag";
import { Menu } from "primereact/menu";
import { Toast } from "primereact/toast";
import { ConfirmDialog, confirmDialog } from "primereact/confirmdialog";
import { FilterMatchMode } from "primereact/api";
import VoucherService, { Voucher } from "@/services/VoucherService";
import VoucherFormDialog from "@/components/vouchers/VoucherFormDialog";

export default function VoucherListPage() {
  const toast = useRef<Toast>(null);
  const menu = useRef<Menu>(null);
  const voucherService = new VoucherService();

  const [vouchers, setVouchers] = useState<Voucher[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedVoucher, setSelectedVoucher] = useState<Voucher | null>(null);
  const [globalFilterValue, setGlobalFilterValue] = useState("");
  const [showDialog, setShowDialog] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [filters, setFilters] = useState({
    global: { value: null, matchMode: FilterMatchMode.CONTAINS },
    code: { value: null, matchMode: FilterMatchMode.STARTS_WITH },
    title: { value: null, matchMode: FilterMatchMode.CONTAINS },
  });

  const menuItems = [
    {
      label: "Edit",
      icon: "pi pi-pencil",
      command: () => {
        if (selectedVoucher) {
          setEditMode(true);
          setShowDialog(true);
        }
      },
    },
    {
      label: "Delete",
      icon: "pi pi-trash",
      command: () => {
        if (selectedVoucher) {
          confirmDelete(selectedVoucher);
        }
      },
    },
  ];

  useEffect(() => {
    loadVouchers();
  }, []);

  const loadVouchers = async () => {
    try {
      setLoading(true);
      const data = await voucherService.getAllVouchers();
      setVouchers(data || []);
    } catch (error) {
      console.error("Failed to load vouchers:", error);
      toast.current?.show({
        severity: "error",
        summary: "Error",
        detail: "Failed to load vouchers",
        life: 3000,
      });
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = () => {
    setSelectedVoucher(null);
    setEditMode(false);
    setShowDialog(true);
  };

  const confirmDelete = (voucher: Voucher) => {
    confirmDialog({
      message: `Are you sure you want to delete voucher "${voucher.code}"?`,
      header: "Confirm Deletion",
      icon: "pi pi-exclamation-triangle",
      acceptClassName: "p-button-danger",
      accept: () => handleDelete(voucher),
    });
  };

  const handleDelete = async (voucher: Voucher) => {
    try {
      await voucherService.deleteVoucher(voucher.id);
      toast.current?.show({
        severity: "success",
        summary: "Success",
        detail: `Voucher "${voucher.code}" deleted successfully`,
        life: 3000,
      });
      loadVouchers();
    } catch (error: any) {
      toast.current?.show({
        severity: "error",
        summary: "Delete Failed",
        detail: error.message || "Failed to delete voucher",
        life: 3000,
      });
    }
  };

  const onGlobalFilterChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    const _filters: any = { ...filters };
    _filters.global.value = value;
    setFilters(_filters);
    setGlobalFilterValue(value);
  };

  const clearFilter = () => {
    setGlobalFilterValue("");
    setFilters({
      global: { value: null, matchMode: FilterMatchMode.CONTAINS },
      code: { value: null, matchMode: FilterMatchMode.STARTS_WITH },
      title: { value: null, matchMode: FilterMatchMode.CONTAINS },
    });
  };

  const toggleMenu = (event: React.MouseEvent, voucher: Voucher) => {
    setSelectedVoucher(voucher);
    menu.current?.toggle(event);
  };

  const statusBodyTemplate = (rowData: Voucher) => {
    return (
      <Tag
        value={rowData.is_active ? "Active" : "Inactive"}
        severity={rowData.is_active ? "success" : "danger"}
      />
    );
  };

  const discountBodyTemplate = (rowData: Voucher) => {
    return rowData.discount_type === "PERCENTAGE"
      ? `${rowData.discount_value}%`
      : `₦${rowData.discount_value.toLocaleString()}`;
  };

  const usageBodyTemplate = (rowData: Voucher) => {
    const usageLimit = rowData.usage_limit || "Unlimited";
    return `${rowData.used_count} / ${usageLimit}`;
  };

  const dateBodyTemplate = (rowData: Voucher, field: string) => {
    const date = rowData[field as keyof Voucher] as string;
    return new Date(date).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  const actionBodyTemplate = (rowData: Voucher) => {
    return (
      <Button
        icon="pi pi-ellipsis-v"
        rounded
        text
        onClick={(e) => toggleMenu(e, rowData)}
      />
    );
  };

  const header = (
    <div className="flex justify-content-between flex-column sm:flex-row">
      <div className="flex gap-2 mb-2">
        <Button
          type="button"
          icon="pi pi-filter-slash"
          label="Clear"
          outlined
          onClick={clearFilter}
        />
        <Button
          type="button"
          icon="pi pi-plus"
          label="New Voucher"
          onClick={handleCreate}
        />
      </div>
      <span className="p-input-icon-left mb-2">
        <i className="pi pi-search" />
        <InputText
          value={globalFilterValue}
          onChange={onGlobalFilterChange}
          placeholder="Search vouchers..."
          style={{ width: "100%" }}
        />
      </span>
    </div>
  );

  return (
    <div className="grid">
      <Toast ref={toast} />
      <ConfirmDialog />

      <div className="col-12">
        <div className="card">
          <h5>Voucher Management</h5>
          <DataTable
            value={vouchers}
            paginator
            rows={10}
            dataKey="id"
            filters={filters}
            filterDisplay="menu"
            loading={loading}
            responsiveLayout="scroll"
            globalFilterFields={["code", "title", "description"]}
            header={header}
            emptyMessage="No vouchers found."
            rowHover
          >
            <Column
              field="code"
              header="Code"
              sortable
              filter
              filterPlaceholder="Search by code"
              style={{ minWidth: "12rem" }}
            />
            <Column
              field="title"
              header="Title"
              sortable
              filter
              filterPlaceholder="Search by title"
              style={{ minWidth: "14rem" }}
            />
            <Column
              field="discount_value"
              header="Discount"
              body={discountBodyTemplate}
              sortable
              style={{ minWidth: "10rem" }}
            />
            <Column
              field="used_count"
              header="Usage"
              body={usageBodyTemplate}
              style={{ minWidth: "10rem" }}
            />
            <Column
              field="valid_from"
              header="Valid From"
              body={(rowData) => dateBodyTemplate(rowData, "valid_from")}
              sortable
              style={{ minWidth: "10rem" }}
            />
            <Column
              field="valid_until"
              header="Valid Until"
              body={(rowData) => dateBodyTemplate(rowData, "valid_until")}
              sortable
              style={{ minWidth: "10rem" }}
            />
            <Column
              field="is_active"
              header="Status"
              body={statusBodyTemplate}
              sortable
              style={{ minWidth: "8rem" }}
            />
            <Column
              body={actionBodyTemplate}
              exportable={false}
              style={{ minWidth: "8rem" }}
              header="Action"
            />
          </DataTable>

          <Menu model={menuItems} popup ref={menu} />
        </div>
      </div>

      <VoucherFormDialog
        visible={showDialog}
        editMode={editMode}
        voucher={selectedVoucher}
        onHide={() => setShowDialog(false)}
        onSave={loadVouchers}
        toast={toast}
      />
    </div>
  );
}
