// src/components/layout/AppTopbar.tsx
"use client";

import Link from "next/link";
import Image from "next/image";

interface AppTopbarProps {
  onMenuToggle: (event: React.MouseEvent) => void;
}

export default function AppTopbar({ onMenuToggle }: AppTopbarProps) {
  return (
    <div className="layout-topbar">
      <Link href="/" className="layout-topbar-logo">
        <Image
          src="/images/logo-dark.svg"
          alt="Logo"
          width={47}
          height={35}
          priority
        />
        <span>SONIC ADMIN</span>
      </Link>
      
      <button
        className="p-link layout-menu-button layout-topbar-button"
        onClick={onMenuToggle}
        type="button"
      >
        <i className="pi pi-bars" />
      </button>

      <button
        className="p-link layout-topbar-menu-button layout-topbar-button"
        type="button"
      >
        <i className="pi pi-ellipsis-v" />
      </button>

      <ul className="layout-topbar-menu hidden lg:flex origin-top">
        <li>
          <button className="p-link layout-topbar-button" type="button">
            <i className="pi pi-calendar" />
            <span>Events</span>
          </button>
        </li>
        <li>
          <button className="p-link layout-topbar-button" type="button">
            <i className="pi pi-cog" />
            <span>Settings</span>
          </button>
        </li>
        <li>
          <button className="p-link layout-topbar-button" type="button">
            <i className="pi pi-user" />
            <span>Profile</span>
          </button>
        </li>
      </ul>
    </div>
  );
}

// src/components/layouts/default/AppTopbar.vue
<script lang="ts">
export default {
  emits: ['topbarMenuToggle', 'menuToggle'],
  computed: {
    darkTheme() {
      return this.$appState.darkTheme;
    }
  },
  methods: {
    onMenuToggle(event) {
      this.$emit('menuToggle', event);
    },
    onTopbarMenuToggle(event) {
      this.$emit('topbarMenuToggle', event);
    },
    topbarImage() {
      return this.$appState.darkTheme ? '/images/logo-white.svg' : '/images/logo-dark.svg';
    }
  }
};
</script>

<template>
  <div class="layout-topbar">
    <NuxtLink to="/" class="layout-topbar-logo">
      <img alt="Logo" :src="topbarImage()">
      <span>SONIC ADMIN</span>
    </NuxtLink>
    <button class="p-link layout-menu-button layout-topbar-button" @click="onMenuToggle">
      <i class="pi pi-bars" />
    </button>

    <button
      v-styleclass="{
        selector: '@next',
        enterClass: 'hidden',
        enterActiveClass: 'scalein',
        leaveToClass: 'hidden',
        leaveActiveClass: 'fadeout',
        hideOnOutsideClick: true
      }"
      class="p-link layout-topbar-menu-button layout-topbar-button"
    >
      <i class="pi pi-ellipsis-v" />
    </button>
    <ul class="layout-topbar-menu hidden lg:flex origin-top">
      <li>
        <button class="p-link layout-topbar-button">
          <i class="pi pi-calendar" />
          <span>Events</span>
        </button>
      </li>
      <li>
        <button class="p-link layout-topbar-button">
          <i class="pi pi-cog" />
          <span>Settings</span>
        </button>
      </li>
      <li>
        <button class="p-link layout-topbar-button">
          <i class="pi pi-user" />
          <span>Profile</span>
        </button>
      </li>
    </ul>
  </div>
</template>
